"""Adiciona campo partnersteamid à tabela trade_offers

Revision ID: 0a25a39cd7f4
Revises: 305f3543bca4
Create Date: 2025-05-16 17:47:46.359744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a25a39cd7f4'
down_revision = '305f3543bca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partnersteamid', sa.String(length=50), nullable=False))
        batch_op.drop_column('steamid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steamid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('partnersteamid')

    # ### end Alembic commands ###
