"""Cria tabelas e relacionamentos para sistema de trade e pagamento

Revision ID: 305f3543bca4
Revises: 377720d20ce2
Create Date: 2025-05-16 16:34:32.448606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305f3543bca4'
down_revision = '377720d20ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informacoes_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=50), nullable=False),
    sa.Column('tradelink', sa.String(length=255), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('chave_pix', sa.String(length=255), nullable=True),
    sa.Column('banco', sa.String(length=255), nullable=True),
    sa.Column('agencia', sa.String(length=50), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('tipo_conta', sa.String(length=50), nullable=True),
    sa.Column('carteira', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid')
    )
    op.create_table('saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid')
    )
    op.create_table('skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradeofferid', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('raridade', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('assetid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradeofferid', sa.String(length=50), nullable=False),
    sa.Column('steamid', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cancelado_por', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('trade_offers')
    op.drop_table('skins')
    op.drop_table('saldos')
    op.drop_table('informacoes_pagamento')
    # ### end Alembic commands ###
