"""Adiciona campo cancelado_por em TradeOffer

Revision ID: 377720d20ce2
Revises: 
Create Date: 2025-02-05 17:00:01.494643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377720d20ce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('usuarios')
    #op.drop_table('skins')
    #op.drop_table('ofertas')
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado_por', sa.String(length=20), nullable=True))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_offers', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('cancelado_por')

    op.create_table('ofertas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_skin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_skin'], ['skins.id'], name='ofertas_id_skin_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='ofertas_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='ofertas_pkey')
    )
    op.create_table('skins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('raridade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='skins_pkey')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tradelink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('senha_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key')
    )
    # ### end Alembic commands ###
