"""Adiciona tabela de saques

Revision ID: 737433ff7583
Revises: 74ec97590956
Create Date: 2025-06-07 10:38:22.550889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737433ff7583'
down_revision = '74ec97590956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saques')
    # ### end Alembic commands ###
